[versions]
android-gradle-plugin = "8.1.2"
material = "1.10.0"
espresso = "3.4.0"
ksp = "1.9.10-1.0.13"
google-service = "4.3.15"
firebase-bom = "32.7.0"
firebase-crashlytics = "2.9.9"

compose-compiler = "1.5.3"
# compose-bom = "2023.09.00"
compose-bom = "2023.12.00-alpha04"
compose-material3 = "1.2.0-alpha07"
activity-compose = "1.7.2"
compose-stable-marker = "1.0.3"
androidx-hilt-navigation-compose = "1.0.0"
compose-rating-bar = "1.3.4"
compose-toolbar = "2.3.5"
glance = "1.0.0"

orbit = "6.1.0"

androidx-app-compat = "1.6.1"
androidx-core = "1.12.0"
androidx-lifecycle = "2.6.2"
androidx-navigation = "2.7.4"
androidx-constraint-layout = "2.1.4"
androidx-activity-ktx = "1.8.0"
androidx-fragment-ktx = "1.6.1"
androidx-recycler-view = "1.3.1"
androidx-splash-screen = "1.0.1"
androidx-datastore = "1.0.0"

kotlin = "1.9.10"
kotlinx-coroutines = "1.7.3"
kotlinx-serialization-json = "1.5.1"
kotlinx-datetime = "0.4.0"
kotlinx-immutable = "0.3.6"

ktlint = "11.5.1"
detekt = "1.23.1"

retrofit = "2.9.0"
retrofit-kotlinx-serialization-json = "1.0.0"
okhttp = "4.11.0"

hilt = "2.48"
room = "2.5.2"

timber = "5.0.1"
encrypted-datastore = "1.7.21-1.0.8-1.1.0-alpha01"
ted-permission = "3.3.0"
coil = "2.4.0"
lottie = "6.0.0"

oss-plugin = "0.10.6"
oss = "17.0.1"
junit4 = "4.13.2"


protobuf-plugin = "0.9.4"
protobuf = "3.24.4"

espresso-core = "3.5.1"
junit-ktx = "1.1.5"
androidx-test-runner = "1.5.2"
junit = "4.12"

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-service" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }

# Plugins defined by this project
suwiki-android-application = { id = "suwiki.android.application", version = "unspecified" }
suwiki-android-application-compose = { id = "suwiki.android.application.compose", version = "unspecified" }
suwiki-android-library = { id = "suwiki.android.library", version = "unspecified" }
suwiki-android-library-compose = { id = "suwiki.android.library.compose", version = "unspecified" }
suwiki-android-hilt = { id = "suwiki.android.hilt", version = "unspecified" }
suwiki-java-library = { id = "suwiki.java.library", version = "unspecified" }
suwiki-android-feature-compose = { id = "suwiki.android.feature.compose", version = "unspecified" }
suwiki-android-remote = { id = "suwiki.android.remote", version = "unspecified" }
suwiki-android-data = { id = "suwiki.android.data", version = "unspecified" }

[libraries]
# Dependencies of the included build-logic
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "android-gradle-plugin" }
gitlab-detekt-plugin-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-plugin-formatting", version.ref = "detekt" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

###
oss-licenses-plugin = { group = "com.google.android.gms", name = "oss-licenses-plugin", version.ref = "oss-plugin" }

# formatting
detekt-plugin-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }

# compose
# compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-bom = { group = "dev.chrisbanes.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
ui-foundation = { group = "androidx.compose.foundation", name = "foundation" }
material3-compose = { group = "androidx.compose.material3", name = "material3" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-ktx" }
lifecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidx-hilt-navigation-compose" }
compose-stable-marker = { group = "com.github.skydoves", name = "compose-stable-marker", version.ref = "compose-stable-marker" }
compose-rating-bar = { group = "com.github.a914-gowtham", name = "compose-ratingbar", version.ref = "compose-rating-bar" }
compose-toolbar = { group = "me.onebone", name = "toolbar-compose", version.ref="compose-toolbar" }
glance-appwidger = { group = "androidx.glance", name = "glance-appwidget", version.ref = "glance" }
glance-material3 = { group = "androidx.glance", name = "glance-material3", version.ref = "glance" }

orbit-core = { group = "org.orbit-mvi", name = "orbit-core", version.ref = "orbit" }
orbit-viewmodel = { group = "org.orbit-mvi", name = "orbit-viewmodel", version.ref = "orbit" }
orbit-compose = { group = "org.orbit-mvi", name = "orbit-compose", version.ref = "orbit" }
orbit-test = { group = "org.orbit-mvi", name = "orbit-test", version.ref = "orbit" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-testing-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-immutable" }

retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-kotlin-serialization = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofit-kotlinx-serialization-json" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidx-navigation" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidx-navigation" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-app-compat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraint-layout" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidx-activity-ktx" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidx-fragment-ktx" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidx-recycler-view" }
androidx-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-splash-screen" }

google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }

timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
androidx-datastore-core = { group = "androidx.datastore", name = "datastore", version.ref = "androidx-datastore" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidx-datastore" }
encrypted-datastore-preference-ksp = { group = "tech.thdev", name = "useful-encrypted-data-store-preferences-ksp", version.ref = "encrypted-datastore" }
encrypted-datastore-preference-ksp-annotations = { group = "tech.thdev", name = "useful-encrypted-data-store-preferences-ksp-annotations", version.ref = "encrypted-datastore" }
encrypted-datastore-preference-security = { group = "tech.thdev", name = "useful-encrypted-data-store-preferences-security", version.ref = "encrypted-datastore" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-database = { group = "com.google.firebase", name = "firebase-database-ktx" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }

ted-permission = { group = "io.github.ParkSangGwon", name = "tedpermission-normal", version.ref = "ted-permission" }
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }

room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }

oss-licenses = { group = "com.google.android.gms", name = "play-services-oss-licenses", version.ref = "oss" }

junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junit-ktx" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

protobuf-kotlin-lite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobuf" }
protobuf-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[bundles]
firebase = ["firebase-analytics", "firebase-database"]
androidx-lifecycle = ["androidx-lifecycle-runtime-ktx", "androidx-lifecycle-viewmodel-ktx"]
androidx-navigation = ["navigation-fragment-ktx", "navigation-ui-ktx"]
coroutine = ["kotlinx-coroutines-android", "kotlinx-coroutines-core"]
compose = ["ui", "ui-graphics", "ui-tooling-preview", "material3-compose", "coil-compose", "ui-foundation", "activity-compose", "lifecycle-compose", "navigation-compose", "hilt-navigation-compose"]
compose-debug = ["ui-tooling", "ui-test-manifest"]
glance = ["glance-appwidger", "glance-material3"]

orbit = ["orbit-core", "orbit-viewmodel", "orbit-compose"]
